---
- name: Restart PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Restart Redis
  ansible.builtin.service:
    name: redis-server
    state: restarted

- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Paperless
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  loop:
    - paperless-webserver
    - paperless-worker
    - paperless-scheduler

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Reload Nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  become: true