---
paperless_version: "2.7.2"
paperless_install_dir: "/opt/paperless"
paperless_venv_dir: "/opt/python-venv/paperless"
paperless_db_engine: "django.db.backends.postgresql"
paperless_db_name: "paperless"
paperless_db_user: "paperless"
paperless_db_pass: "linuxfabrik"
paperless_redis_host: "127.0.0.1"
paperless_redis_port: 6379
paperless_ocr_language: "deu+eng"
paperless_time_zone: "Europe/Berlin"
paperless_admin_mail: admin@example.com
paperless_fqdn: "dms.example.com"
paperless_secret_key: "your_super_duper_secret_key"
cloudflare_api_key: "your_cloudflare_api_key_for_https"