---
- name: Create sshd_config from template
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - Restart sshd

- name: Set authorized keys from Repo
  ansible.posix.authorized_key:
    user: heyeradmin
    state: present
    key: https://git.heyer.systems/kevinheyer/trusted-ssh-keys/raw/branch/main/id_kevin_heyer.pub
