---
- name: Include package installation
  ansible.builtin.import_tasks: install_packages.yml

- name: Include unattended upgrades configuration
  ansible.builtin.import_tasks: configure_unattended_upgrades.yml

- name: Include User configuration
  ansible.builtin.import_tasks: configure_user.yml

- name: Include CMDB configuration
  ansible.builtin.import_tasks: configure_cmdb.yml

- name: Include SSH configuration
  ansible.builtin.import_tasks: configure_ssh.yml

- name: Include NTP Configuration
  ansible.builtin.import_tasks: configure_ntp.yml

- name: Include Fail2Ban Configuration
  ansible.builtin.import_tasks: configure_fail2ban.yml

- name: Include Neofetch Configuration
  ansible.builtin.import_tasks: configure_neofetch.yml