---
- name: Create Paperless directories
  file:
    path: "{{ paperless_install_dir }}/{{ item }}"
    state: directory
    owner: paperless
    group: paperless
    mode: 0755
    recurse: true
  loop:
    - consume
    - data
    - trash
    - media
    - static

- name: Ensure venv directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ paperless_venv_dir }}"
    state: directory
    owner: paperless
    group: paperless
    mode: '0755'
    recurse: yes
  become: true