- name: Create Directory for GPG-Keys
  ansible.builtin.file:
    path: /usr/share/postgresql-common/pgdg
    state: directory
    mode: '0755'

- name: Import PostgreSQL GPG-Key
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    mode: '0644'

- name: Add PostgreSQL Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] http://apt.postgresql.org/pub/repos/apt {{ ansible_facts['distribution_release'] }}-pgdg main"
    state: present
    filename: pgdg

- name: Install PostgreSQL and Dependencies
  ansible.builtin.apt:
    name:
      - postgresql-16
      - python3-psycopg2
    state: present
    update_cache: true

- name: Start and Enable PostgreSQL Service
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Configure pg_hba.conf for paperless (Peer Auth)
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: local
    users: paperless
    databases: paperless
    method: peer
    state: present
  become: true
  become_user: postgres
  notify: Restart PostgreSQL

- name: Create PostgreSQL-User 'paperless'
  community.postgresql.postgresql_user:
    name: paperless
    role_attr_flags: NOSUPERUSER,CREATEDB
  become: true
  become_user: postgres

- name: Create PostgreSQL-Database 'paperless'
  community.postgresql.postgresql_db:
    name: paperless
    owner: paperless
  become: true
  become_user: postgres