---
all:
  children:

    router:
      hosts:
        router1.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/router1.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/router1.intra.heyer.systems')['ansible_user'] }}"

    proxmox:
      hosts:
        pve1.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve1.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve1.intra.heyer.systems')['ansible_user'] }}"
        pve2.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve2.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve2.intra.heyer.systems')['ansible_user'] }}"
        pve3.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve3.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve3.intra.heyer.systems')['ansible_user'] }}"
        pve4.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve4.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/pve4.intra.heyer.systems')['ansible_user'] }}"
        pbs.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/pbs.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/pbs.intra.heyer.systems')['ansible_user'] }}"

    unraid:
      hosts:
        nas1.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/nas1.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/nas1.intra.heyer.systems')['ansible_user'] }}"

    vms:
      hosts:
        terraform.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/terraform.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/terraform.intra.heyer.systems')['ansible_user'] }}"
        dms.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/dms.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/dms.intra.heyer.systems')['ansible_user'] }}"
        game.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/game.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/game.intra.heyer.systems')['ansible_user'] }}"
        docker-external.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/docker-external.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/docker-external.intra.heyer.systems')['ansible_user'] }}"
        docker-internal.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/docker-internal.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/docker-internal.intra.heyer.systems')['ansible_user'] }}"
        dns.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/dns.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/dns.intra.heyer.systems')['ansible_user'] }}"
        vault.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/vault.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/vault.intra.heyer.systems')['ansible_user'] }}"
        builder.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/builder.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/builder.intra.heyer.systems')['ansible_user'] }}"
        hass.intra.heyer.systems:
          ansible_host: "{{ lookup('openbao', 'secret=ansible/production/hosts/hass.intra.heyer.systems')['ansible_host'] }}"
          ansible_user: "{{ lookup('openbao', 'secret=ansible/production/hosts/hass.intra.heyer.systems')['ansible_user'] }}"
